name: ci

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node env
        uses: actions/setup-node@v3.0.0
        with:
          node-version: lts/*
          check-latest: true
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint  
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Setup node env
        uses: actions/setup-node@v3.0.0
        with:
          node-version: lts/*
          check-latest: true
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test 
  deploy: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Setup node env
        uses: actions/setup-node@v3.0.0
        with:
          node-version: lts/*
          check-latest: true
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: heschwerdt/tracking-detector-dashboard:latest